name: "CI/CD for Task Manager"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.3"

      - name: Установка системных зависимостей для PyQt5
        run: |
          sudo apt-get update && sudo apt-get install -y \
            xvfb libgl1-mesa-glx libegl1-mesa libxrender1 libxtst6 libxi6 \
            libnss3 libasound2 libsm6 python3-opengl \
            libxcb1 libx11-dev  # Полный набор зависимостей

      - name: Установка пакетов
        run: |
          pip install -r requirements.txt
          pip install coverage PyQt5==5.15.17  # Указана совместимая версия

      - name: Запуск тестов с эмуляцией GUI
        run: |
          export DISPLAY=:99  # Настройка Xvfb
          Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &  # Расширенные настройки
          sleep 5  # Даем время на стабилизацию Xvfb
          coverage run -m unittest discover -s tests  # Запуск через unittest
          coverage html
          pkill Xvfb

      - name: Проверка генерации отчета
        run: |
          if [ ! -f htmlcov/index.html ]; then exit 1; fi  # Остановка workflow, если отчет не сгенерирован

      - name: Загрузка отчета
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

      - name: Проверка успеха
        if: failure()
        run: echo "Тесты провалились. Проверьте логи."