name: "CI/CD for Task Manager"  # Название workflow 

on:  # Триггеры для запуска workflow
  push:  # При push в ветку master
    branches:
      - master
  pull_request:  # При создании pull request в master
    branches:
      - master # Триггер при создании PR в master

jobs:  # Определение заданий
  build-and-test:  # Имя задания
    runs-on: ubuntu-latest  # Операционная система для выполнения 
    steps:  # Последовательность шагов
      - name: Checkout code  # Клонирование репозитория
        uses: actions/checkout@v4  # Использует стандартный action для клонирования 

      - name: Set up Python  # Настройка окружения Python
        uses: actions/setup-python@v5  # Установка Python через action 
        with:
          python-version: "3.13.3"  # Версия Python согласно требованиям 

      - name: Установка системных зависимостей для PyQt5
        run: |
          sudo apt-get update && sudo apt-get install -y \
            xvfb libgl1 libegl1 libxcb1 libx11-dev libxrender1 libxtst6 libxi6 \
            libnss3 libasound2 libsm6 python3-opengl  # Добавлен libsm6 и libxrender1
          sudo apt-get install -y python3-xvfb  # Дополнительный пакет для эмуляции

      - name: Установка пакетов
        run: |
          pip install -r requirements.txt
          pip install coverage PyQt5==5.15.17  # Указана конкретная совместимая версия

      - name: Run tests with coverage  # Запуск тестов
        run: |  # Команды для выполнения тестов
          export DISPLAY=:99  # Настройка Xvfb
          Xvfb :99 -screen 0 1024x768x24 &  # Запуск эмулятора
          sleep 3  # Ждем стабилизации Xvfb
          coverage run -m unittest discover -s tests  # Запуск через unittest
          coverage html
          pkill Xvfb  # Остановка Xvfb после тестов

      - name: Проверка успешности тестов
        run: |
          if [ ! -f htmlcov/index.html ]; then exit 1; fi  # Проверка генерации отчета

      - name: Upload coverage report  # Сохранение отчета как артефакта
        uses: actions/upload-artifact@v4  # Action для загрузки результатов 
        with:
          name: coverage-report  # Имя артефакта
          path: htmlcov/  # Путь к сгенерированному отчету

      - name: Show test results  # Вывод содержимого отчета в логи
        run: cat htmlcov/index.html  # Просмотр содержимого файла

      - name: Check test success  # Проверка на провал тестов
        if: failure()  # Условие выполнения: если предыдущие шаги провалились
        run: echo "Тесты провалились. Проверьте логи."  # Вывод ошибки
