name: "CI/CD for Task Manager"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Установка системных зависимостей
        run: |
          sudo apt-get update && sudo apt-get install -y \
            xvfb libgl1-mesa-glx libegl1-mesa libxrender1 libxtst6 libxi6 \
            libnss3 libasound2 libsm6 python3-opengl \
            libxcb-xinerama0 libxcb-randr0 libxcb-shape0 libxcb-xfixes0 \
            libxkbcommon0 libglvnd0 libgles2-mesa

      - name: Запуск эмуляции GUI
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1280x1024x24 -ac +extension GLX +render -noreset &  
          sleep 10

      - name: Установка пакетов
        run: |
          pip install -r requirements.txt
          pip install coverage==7.8.2 PyQt5==5.15.17

      - name: Запуск тестов
        run: |
          coverage run -m unittest discover -s tests
          coverage html
          pkill Xvfb

      - name: Проверка отчета
        run: cat htmlcov/index.html

      - name: Загрузка артефакта
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/