name: "CI/CD for Task Manager"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.3"

      - name: Установка системных зависимостей
        run: |
          sudo apt-get update && sudo apt-get install -y \
            xvfb libgl1-mesa-glx libegl1-mesa libxrender1 libxtst6 libxi6 \
            libnss3 libasound2 libsm6 python3-opengl

      - name: Установка пакетов
        run: |
          pip install -r requirements.txt
          pip install coverage PyQt5==5.15.17  # Указываем конкретную версию

      - name: Запуск тестов с эмуляцией GUI
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1280x1024x24 -ac +extension GLX +render -noreset &  
          sleep 5
          coverage run -m unittest discover -s tests  # Запуск через unittest
          coverage html
          pkill Xvfb

      - name: Загрузка отчета
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/